name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.16.x, 1.17.x, 1.18.x, 1.19.x]

    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get Go dependencies
      run: |
        cd ./src/function
        go get -v -t -d ./...

    - name: Build
      run: |
        cd ./src/function
        go build ./...

    - name: "Check: go fmt"
      run: |
        cd ./src/function
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            gofmt -s -l -d .
            echo "Please run: go fmt ./..."
            exit 1
        fi
        if [ "$(go mod tidy -v | wc -l)" -gt 0 ]; then
            go mod tidy -v
            echo "Please run: go mod tidy"
            exit 1
        fi
